version: "3.9"

services:
  web:
    build: .
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}
