"""Initial migration

Revision ID: 89d0f5b017bf
Revises: e65ce4a1588f
Create Date: 2024-12-26 15:16:49.753675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d0f5b017bf'
down_revision: Union[str, None] = 'e65ce4a1588f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('chapters', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chapters', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('chapters', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('chats', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('chats', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('classes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('classes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('classes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('classes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('education_levels', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('education_levels', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('education_levels', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('education_levels', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('subjects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('subjects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('topics', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('topics', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('topics', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('type', sa.Enum('superadmin', 'admin', 'staff', 'normal', name='user_type'), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_normal', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_normal')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'type')
    op.drop_column('topics', 'deleted_at')
    op.drop_column('topics', 'updated_at')
    op.drop_column('topics', 'created_at')
    op.drop_column('topics', 'is_deleted')
    op.drop_column('subjects', 'deleted_at')
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'created_at')
    op.drop_column('subjects', 'is_deleted')
    op.drop_column('sessions', 'deleted_at')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'is_deleted')
    op.drop_column('education_levels', 'deleted_at')
    op.drop_column('education_levels', 'updated_at')
    op.drop_column('education_levels', 'created_at')
    op.drop_column('education_levels', 'is_deleted')
    op.drop_column('classes', 'deleted_at')
    op.drop_column('classes', 'updated_at')
    op.drop_column('classes', 'created_at')
    op.drop_column('classes', 'is_deleted')
    op.drop_column('chats', 'deleted_at')
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'is_deleted')
    op.drop_column('chapters', 'deleted_at')
    op.drop_column('chapters', 'updated_at')
    op.drop_column('chapters', 'created_at')
    op.drop_column('chapters', 'is_deleted')
    # ### end Alembic commands ###
