"""Initial migration

Revision ID: dcdaa07903b6
Revises: 
Create Date: 2024-12-20 12:57:50.139552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdaa07903b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'image_link')
    op.drop_column('topics', 'tagline')
    op.drop_column('subjects', 'image_link')
    op.drop_column('subjects', 'tagline')
    op.drop_column('classes', 'image_link')
    op.drop_column('classes', 'tagline')
    op.drop_column('chapters', 'image_link')
    op.drop_column('chapters', 'tagline')
    # ### end Alembic commands ###
