"""Initial migration

Revision ID: e2d7937ec4ff
Revises: 38fcfee307f3
Create Date: 2024-12-24 18:27:08.795283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d7937ec4ff'
down_revision: Union[str, None] = '38fcfee307f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'education_levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'level_id')
    # ### end Alembic commands ###
